// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UFF.FichaAnestesica.Infra.Context;

#nullable disable

namespace UFF.FichaAnestesica.Infra.Migrations
{
    [DbContext(typeof(SigaDbCtx))]
    [Migration("20260823181739_AddUserSettingsAndInstitutionSettings")]
    partial class AddUserSettingsAndInstitutionSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("siga_db")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdministeredAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal>("Dose")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("dose");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer")
                        .HasColumnName("drug_id");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<int>("Route")
                        .HasColumnType("integer")
                        .HasColumnName("route");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<int>("Unit")
                        .HasColumnType("integer")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("DrugId");

                    b.HasIndex("MonitoringRecordId");

                    b.ToTable("administered_agents", "siga_db");
                });

            modelBuilder.Entity("AnesthesiaRecordSurgery", b =>
                {
                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("integer")
                        .HasColumnName("procedure_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.HasKey("AnesthesiaRecordId", "ProcedureId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("anesthesia_record_procedures", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("ActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("activity_score");

                    b.Property<string>("AirwayDeviceNumbers")
                        .HasColumnType("jsonb")
                        .HasColumnName("airway_device_numbers");

                    b.Property<int?>("AirwayType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_type");

                    b.Property<TimeOnly?>("AldreteEvaluationTime")
                        .HasColumnType("time")
                        .HasColumnName("aldrete_evaluation_time");

                    b.Property<TimeOnly?>("AnesthesiaEndTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_end_time");

                    b.Property<bool?>("AnesthesiaEquipmentChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthesia_equipment_checked");

                    b.Property<TimeOnly?>("AnesthesiaStartTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_start_time");

                    b.Property<bool?>("AnestheticConsentSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthetic_consent_signed");

                    b.Property<int?>("AsaClassification")
                        .HasColumnType("integer")
                        .HasColumnName("asa_classification");

                    b.Property<int?>("AssistantId")
                        .HasColumnType("integer")
                        .HasColumnName("assistant_id");

                    b.Property<string>("BloodPressure")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<bool?>("Bronchofibroscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("bronchofibroscopy");

                    b.Property<int?>("CirculationScore")
                        .HasColumnType("integer")
                        .HasColumnName("circulation_score");

                    b.Property<int?>("ClinicalDischargeCondition")
                        .HasColumnType("integer")
                        .HasColumnName("clinical_discharge_condition");

                    b.Property<bool?>("Co2AbsorberCircuit")
                        .HasColumnType("boolean")
                        .HasColumnName("co2_absorber_circuit");

                    b.Property<string>("Conduta")
                        .HasColumnType("text")
                        .HasColumnName("conduta");

                    b.Property<int?>("ConsciousnessScore")
                        .HasColumnType("integer")
                        .HasColumnName("consciousness_score");

                    b.Property<int?>("ControlledVentilationMode")
                        .HasColumnType("integer")
                        .HasColumnName("controlled_ventilation_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool?>("Cuff")
                        .HasColumnType("boolean")
                        .HasColumnName("cuff");

                    b.Property<string>("CushionsAccessLocation")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cushions_access_location");

                    b.Property<int?>("Destination")
                        .HasColumnType("integer")
                        .HasColumnName("destination");

                    b.Property<bool?>("DifficultVenousPuncture")
                        .HasColumnType("boolean")
                        .HasColumnName("difficult_venous_puncture");

                    b.Property<string>("DischargeConditionOther")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("discharge_condition_other");

                    b.Property<int?>("DorBPS")
                        .HasColumnType("integer")
                        .HasColumnName("dor_bps");

                    b.Property<int?>("DorENV")
                        .HasColumnType("integer")
                        .HasColumnName("dor_env");

                    b.Property<int?>("DorPAINAD")
                        .HasColumnType("integer")
                        .HasColumnName("dor_painad");

                    b.Property<bool?>("DorUsouBPS")
                        .HasColumnType("boolean")
                        .HasColumnName("dor_usou_bps");

                    b.Property<bool?>("DorUsouENV")
                        .HasColumnType("boolean")
                        .HasColumnName("dor_usou_env");

                    b.Property<bool?>("DorUsouPAINAD")
                        .HasColumnType("boolean")
                        .HasColumnName("dor_usou_painad");

                    b.Property<int?>("FirstAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("first_anesthesiologist_id");

                    b.Property<bool?>("GeneralAnesthesia")
                        .HasColumnType("boolean")
                        .HasColumnName("general_anesthesia");

                    b.Property<bool?>("HasOtherAirwayTechnique")
                        .HasColumnType("boolean")
                        .HasColumnName("has_other_airway_technique");

                    b.Property<bool?>("HasOxygenSupplementationOther")
                        .HasColumnType("boolean")
                        .HasColumnName("has_oxygen_supplementation_other");

                    b.Property<bool?>("HasPain")
                        .HasColumnType("boolean")
                        .HasColumnName("has_pain");

                    b.Property<int?>("IntubationDifficulty")
                        .HasColumnType("integer")
                        .HasColumnName("intubation_difficulty");

                    b.Property<bool?>("Iot")
                        .HasColumnType("boolean")
                        .HasColumnName("iot");

                    b.Property<bool?>("Laryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("laryngoscopy");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<bool?>("NasalTube")
                        .HasColumnType("boolean")
                        .HasColumnName("nasal_tube");

                    b.Property<bool?>("NeurostimulatorUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("neurostimulator_used");

                    b.Property<bool?>("OralTube")
                        .HasColumnType("boolean")
                        .HasColumnName("oral_tube");

                    b.Property<string>("OtherAirwayTechnique")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_technique");

                    b.Property<string>("OtherAirwayTypeDescription")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_type_description");

                    b.Property<string>("OtherSurgicalPosition")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_surgical_position");

                    b.Property<string>("OtherVenousAccess")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("other_venous_access");

                    b.Property<int?>("OxygenSaturation")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation");

                    b.Property<int?>("OxygenSaturationScore")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation_score");

                    b.Property<bool?>("OxygenSupplementation")
                        .HasColumnType("boolean")
                        .HasColumnName("oxygen_supplementation");

                    b.Property<string>("OxygenSupplementationOther")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("oxygen_supplementation_other");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("patient_id");

                    b.Property<bool?>("PatientIdentifiedBeforeInduction")
                        .HasColumnType("boolean")
                        .HasColumnName("patient_identified_before_induction");

                    b.Property<bool?>("PlexusBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("plexus_block_performed");

                    b.Property<string>("PostOperativeDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("post_operative_diagnosis");

                    b.Property<bool?>("PreAnestheticMedication")
                        .HasColumnType("boolean")
                        .HasColumnName("pre_anesthetic_medication");

                    b.Property<string>("PreAnestheticMedicationDose")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pre_anesthetic_medication_dose");

                    b.Property<int?>("PreAnestheticMedicationId")
                        .HasColumnType("integer")
                        .HasColumnName("pre_anesthetic_medication_id");

                    b.Property<string>("PreAnestheticMedicationName")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("pre_anesthetic_medication_name");

                    b.Property<string>("PreAnestheticMedicationOtherRoute")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pre_anesthetic_medication_other_route");

                    b.Property<string>("PreAnestheticMedicationRoute")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pre_anesthetic_medication_route");

                    b.Property<TimeOnly?>("PreAnestheticMedicationTime")
                        .HasColumnType("time")
                        .HasColumnName("pre_anesthetic_medication_time");

                    b.Property<string>("PreOperativeDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("pre_operative_diagnosis");

                    b.Property<bool>("ProceduresCustomized")
                        .HasColumnType("boolean")
                        .HasColumnName("procedures_customized");

                    b.Property<bool?>("ProphylacticAntibioticUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("prophylactic_antibiotic_used");

                    b.Property<int?>("PunctureCount")
                        .HasColumnType("integer")
                        .HasColumnName("puncture_count");

                    b.Property<int?>("PuncturePosition")
                        .HasColumnType("integer")
                        .HasColumnName("puncture_position");

                    b.Property<int?>("RespirationMode")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_mode");

                    b.Property<int?>("RespirationScore")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_score");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<bool?>("RetrogradeTechnique")
                        .HasColumnType("boolean")
                        .HasColumnName("retrograde_technique");

                    b.Property<TimeOnly?>("RoomEntryTime")
                        .HasColumnType("time")
                        .HasColumnName("room_entry_time");

                    b.Property<string>("SafetyObservations")
                        .HasColumnType("text")
                        .HasColumnName("safety_observations");

                    b.Property<int?>("SecondAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("second_anesthesiologist_id");

                    b.Property<bool?>("SedationPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("sedation_performed");

                    b.Property<DateTime?>("SignatureDate")
                        .HasColumnType("date")
                        .HasColumnName("signature_date");

                    b.Property<bool?>("SpinalBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("spinal_block_performed");

                    b.Property<bool?>("SpinalCatheter")
                        .HasColumnType("boolean")
                        .HasColumnName("spinal_catheter");

                    b.Property<bool?>("SpinalOpioid")
                        .HasColumnType("boolean")
                        .HasColumnName("spinal_opioid");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("SurgeonId")
                        .HasColumnType("integer")
                        .HasColumnName("surgeon_id");

                    b.Property<DateTime>("SurgeryDate")
                        .HasColumnType("date")
                        .HasColumnName("surgery_date");

                    b.Property<TimeOnly?>("SurgeryEndTime")
                        .HasColumnType("time")
                        .HasColumnName("surgery_end_time");

                    b.Property<string>("SurgeryPerformed")
                        .HasColumnType("text")
                        .HasColumnName("surgery_performed");

                    b.Property<int?>("SurgicalPosition")
                        .HasColumnType("integer")
                        .HasColumnName("surgical_position");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<int?>("TotalAldreteKroulikScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_aldrete_kroulik_score");

                    b.Property<bool?>("Tracheostomy")
                        .HasColumnType("boolean")
                        .HasColumnName("tracheostomy");

                    b.Property<bool?>("UsesCushions")
                        .HasColumnType("boolean")
                        .HasColumnName("uses_cushions");

                    b.Property<string>("VenousAccessLocation")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("venous_access_location");

                    b.Property<int?>("VenousAccessType")
                        .HasColumnType("integer")
                        .HasColumnName("venous_access_type");

                    b.Property<bool?>("VideoLaryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("video_laryngoscopy");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("AssistantId");

                    b.HasIndex("FirstAnesthesiologistId");

                    b.HasIndex("SecondAnesthesiologistId");

                    b.HasIndex("SurgeonId");

                    b.ToTable("anesthesia_records", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAirwayDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<int>("DeviceType")
                        .HasColumnType("integer")
                        .HasColumnName("device_type");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId");

                    b.ToTable("anesthesia_record_airway_devices", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibiotic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dose");

                    b.Property<bool>("HasBooster")
                        .HasColumnType("boolean")
                        .HasColumnName("has_booster");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer")
                        .HasColumnName("medication_id");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("medication_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("route");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId");

                    b.ToTable("anesthesia_record_antibiotics", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibioticBooster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordAntibioticId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_antibiotic_id");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dose");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer")
                        .HasColumnName("medication_id");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("medication_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("route");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordAntibioticId");

                    b.ToTable("anesthesia_record_antibiotic_boosters", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordOxygenSupplementation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId");

                    b.ToTable("anesthesia_record_oxygen_supplementations", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordPunctureLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId");

                    b.ToTable("anesthesia_record_puncture_levels", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordStimulatedNerve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<int>("Nerve")
                        .HasColumnType("integer")
                        .HasColumnName("nerve");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId");

                    b.ToTable("anesthesia_record_stimulated_nerves", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.ClinicalEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EventType");

                    b.HasIndex("MonitoringRecordId");

                    b.ToTable("clinical_events", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.CustomField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("value");

                    b.Property<int?>("vital_sign_record_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("vital_sign_record_id");

                    b.ToTable("custom_fields", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("default_unit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("drugs", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.FluidBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<string>("Details")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("details");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<decimal>("VolumeMl")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("volume_ml");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Date");

                    b.HasIndex("MonitoringRecordId");

                    b.HasIndex("Type");

                    b.ToTable("fluid_balances", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.InstitutionSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AghuApiUrl")
                        .HasColumnType("varchar(300)")
                        .HasColumnName("aghu_api_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("HospitalCep")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("hospital_cep");

                    b.Property<string>("HospitalCity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(120)")
                        .HasDefaultValue("Niterói")
                        .HasColumnName("hospital_city");

                    b.Property<string>("HospitalCnpj")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("hospital_cnpj");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("Hospital Universitário Antônio Pedro")
                        .HasColumnName("hospital_name");

                    b.Property<string>("HospitalNeighborhood")
                        .HasColumnType("varchar(120)")
                        .HasColumnName("hospital_neighborhood");

                    b.Property<string>("HospitalNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("hospital_number");

                    b.Property<string>("HospitalSector")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("hospital_sector");

                    b.Property<string>("HospitalState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2)")
                        .HasDefaultValue("RJ")
                        .HasColumnName("hospital_state");

                    b.Property<string>("HospitalStreet")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("hospital_street");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("monitoring_interval_minutes");

                    b.Property<string>("SigaApiUrl")
                        .HasColumnType("varchar(300)")
                        .HasColumnName("siga_api_url");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("institution_settings", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ended_at");

                    b.Property<bool>("IsMonitoringDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_monitoring_draft");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<DateTime?>("MonitoringUpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("monitoring_updated_at");

                    b.Property<int>("RecordedByProfessionalId")
                        .HasColumnType("integer")
                        .HasColumnName("recorded_by_professional_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SurgeryEndedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("surgery_ended_at");

                    b.Property<DateTime?>("SurgeryStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("surgery_started_at");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId")
                        .IsUnique();

                    b.HasIndex("RecordedByProfessionalId");

                    b.HasIndex("StartedAt");

                    b.ToTable("monitoring_records", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PatientPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<int>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("MonitoringRecordId");

                    b.ToTable("patient_positions", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaComorbidity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<List<string>>("Findings")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("findings");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("group_key");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("OtherDescription")
                        .HasColumnType("text")
                        .HasColumnName("other_description");

                    b.Property<int>("PreAnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("pre_anesthesia_record_id");

                    b.HasKey("Id");

                    b.HasIndex("PreAnesthesiaRecordId");

                    b.ToTable("pre_anesthesia_comorbidities", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Dose")
                        .HasColumnType("text")
                        .HasColumnName("dose");

                    b.Property<string>("Frequency")
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PreAnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("pre_anesthesia_record_id");

                    b.Property<string>("Route")
                        .HasColumnType("text")
                        .HasColumnName("route");

                    b.HasKey("Id");

                    b.HasIndex("PreAnesthesiaRecordId");

                    b.ToTable("pre_anesthesia_medications", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaPhysicalExamArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaKey")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("area_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<List<string>>("Findings")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("findings");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("OtherDescription")
                        .HasColumnType("text")
                        .HasColumnName("other_description");

                    b.Property<int>("PreAnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("pre_anesthesia_record_id");

                    b.HasKey("Id");

                    b.HasIndex("PreAnesthesiaRecordId");

                    b.ToTable("pre_anesthesia_physical_exam_areas", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AirwayMucosa")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("airway_mucosa");

                    b.Property<string>("AirwayObservations")
                        .HasColumnType("text")
                        .HasColumnName("airway_observations");

                    b.Property<string>("AlcoholGramsPerDay")
                        .HasColumnType("text")
                        .HasColumnName("alcohol_grams_per_day");

                    b.Property<bool?>("AlcoholUse")
                        .HasColumnType("boolean")
                        .HasColumnName("alcohol_use");

                    b.Property<string>("AllergyOtherDescription")
                        .HasColumnType("text")
                        .HasColumnName("allergy_other_description");

                    b.Property<string>("AllergyReactionType")
                        .HasColumnType("text")
                        .HasColumnName("allergy_reaction_type");

                    b.Property<List<string>>("AllergySubstances")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allergy_substances");

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<string>("AnestheticHistory")
                        .HasColumnType("text")
                        .HasColumnName("anesthetic_history");

                    b.Property<decimal?>("Aptt")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("aptt");

                    b.Property<int?>("AsaClassification")
                        .HasColumnType("integer")
                        .HasColumnName("asa_classification");

                    b.Property<decimal?>("Bmi")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("bmi");

                    b.Property<string>("ChestXRay")
                        .HasColumnType("text")
                        .HasColumnName("chest_x_ray");

                    b.Property<string>("ComorbiditiesOtherDescription")
                        .HasColumnType("text")
                        .HasColumnName("comorbidities_other_description");

                    b.Property<List<string>>("ConductActions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("conduct_actions");

                    b.Property<string>("ConductNotes")
                        .HasColumnType("text")
                        .HasColumnName("conduct_notes");

                    b.Property<DateOnly?>("ConsultationDate")
                        .HasColumnType("date")
                        .HasColumnName("consultation_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Creatinine")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("creatinine");

                    b.Property<int?>("Dentition")
                        .HasColumnType("integer")
                        .HasColumnName("dentition");

                    b.Property<int?>("DiastolicBloodPressure")
                        .HasColumnType("integer")
                        .HasColumnName("diastolic_blood_pressure");

                    b.Property<bool?>("DifficultIntubationPrediction")
                        .HasColumnType("boolean")
                        .HasColumnName("difficult_intubation_prediction");

                    b.Property<List<string>>("DrugTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("drug_types");

                    b.Property<string>("DrugsOtherDescription")
                        .HasColumnType("text")
                        .HasColumnName("drugs_other_description");

                    b.Property<string>("Ecg")
                        .HasColumnType("text")
                        .HasColumnName("ecg");

                    b.Property<string>("Echocardiogram")
                        .HasColumnType("text")
                        .HasColumnName("echocardiogram");

                    b.Property<string>("FamilyHistory")
                        .HasColumnType("text")
                        .HasColumnName("family_history");

                    b.Property<decimal?>("FastingLiquidsHours")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("fasting_liquids_hours");

                    b.Property<decimal?>("FastingSolidsHours")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("fasting_solids_hours");

                    b.Property<decimal?>("Glucose")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("glucose");

                    b.Property<bool?>("HasAllergy")
                        .HasColumnType("boolean")
                        .HasColumnName("has_allergy");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("height_cm");

                    b.Property<decimal?>("Hematocrit")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hematocrit");

                    b.Property<decimal?>("Hemoglobin")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hemoglobin");

                    b.Property<bool?>("IllicitDrugUse")
                        .HasColumnType("boolean")
                        .HasColumnName("illicit_drug_use");

                    b.Property<int?>("IncisorRelation")
                        .HasColumnType("integer")
                        .HasColumnName("incisor_relation");

                    b.Property<int?>("InterIncisorDistance")
                        .HasColumnType("integer")
                        .HasColumnName("inter_incisor_distance");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("boolean")
                        .HasColumnName("is_emergency");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int?>("Laterality")
                        .HasColumnType("integer")
                        .HasColumnName("laterality");

                    b.Property<decimal?>("Leukocytes")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("leukocytes");

                    b.Property<string>("LiverFunctionTests")
                        .HasColumnType("text")
                        .HasColumnName("liver_function_tests");

                    b.Property<int?>("MallampatiClass")
                        .HasColumnType("integer")
                        .HasColumnName("mallampati_class");

                    b.Property<int?>("MandibleProtrusion")
                        .HasColumnType("integer")
                        .HasColumnName("mandible_protrusion");

                    b.Property<int?>("MandibularSpaceCompliance")
                        .HasColumnType("integer")
                        .HasColumnName("mandibular_space_compliance");

                    b.Property<int?>("NeckExtension")
                        .HasColumnType("integer")
                        .HasColumnName("neck_extension");

                    b.Property<int?>("NeckFlexion")
                        .HasColumnType("integer")
                        .HasColumnName("neck_flexion");

                    b.Property<int?>("NeckLength")
                        .HasColumnType("integer")
                        .HasColumnName("neck_length");

                    b.Property<int?>("NeckWidth")
                        .HasColumnType("integer")
                        .HasColumnName("neck_width");

                    b.Property<bool>("NotCleared")
                        .HasColumnType("boolean")
                        .HasColumnName("not_cleared");

                    b.Property<string>("NotClearedReason")
                        .HasColumnType("text")
                        .HasColumnName("not_cleared_reason");

                    b.Property<string>("OtherImaging")
                        .HasColumnType("text")
                        .HasColumnName("other_imaging");

                    b.Property<int?>("Palate")
                        .HasColumnType("integer")
                        .HasColumnName("palate");

                    b.Property<decimal?>("Platelets")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("platelets");

                    b.Property<decimal?>("Potassium")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("potassium");

                    b.Property<string>("PreOperativeDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("pre_operative_diagnosis");

                    b.Property<string>("PregnancyTest")
                        .HasColumnType("text")
                        .HasColumnName("pregnancy_test");

                    b.Property<string>("ProcedureObservation")
                        .HasColumnType("text")
                        .HasColumnName("procedure_observation");

                    b.Property<string>("PulmonaryFunctionTest")
                        .HasColumnType("text")
                        .HasColumnName("pulmonary_function_test");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("signed_at");

                    b.Property<string>("SignedByName")
                        .HasColumnType("text")
                        .HasColumnName("signed_by_name");

                    b.Property<int?>("SignedByProfessionalId")
                        .HasColumnType("integer")
                        .HasColumnName("signed_by_professional_id");

                    b.Property<bool?>("Smoker")
                        .HasColumnType("boolean")
                        .HasColumnName("smoker");

                    b.Property<string>("SmokingLoad")
                        .HasColumnType("text")
                        .HasColumnName("smoking_load");

                    b.Property<decimal?>("Sodium")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sodium");

                    b.Property<int?>("Spo2")
                        .HasColumnType("integer")
                        .HasColumnName("spo2");

                    b.Property<int?>("SternomentalDistance")
                        .HasColumnType("integer")
                        .HasColumnName("sternomental_distance");

                    b.Property<int?>("SystolicBloodPressure")
                        .HasColumnType("integer")
                        .HasColumnName("systolic_blood_pressure");

                    b.Property<decimal?>("TapInr")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tap_inr");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<bool?>("ThoracicCageAbnormality")
                        .HasColumnType("boolean")
                        .HasColumnName("thoracic_cage_abnormality");

                    b.Property<string>("ThoracicCageAbnormalityDescription")
                        .HasColumnType("text")
                        .HasColumnName("thoracic_cage_abnormality_description");

                    b.Property<int?>("ThyromentalDistance")
                        .HasColumnType("integer")
                        .HasColumnName("thyromental_distance");

                    b.Property<string>("Tp")
                        .HasColumnType("text")
                        .HasColumnName("tp");

                    b.Property<int?>("UpperIncisorLength")
                        .HasColumnType("integer")
                        .HasColumnName("upper_incisor_length");

                    b.Property<decimal?>("Urea")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("urea");

                    b.Property<string>("Urinalysis")
                        .HasColumnType("text")
                        .HasColumnName("urinalysis");

                    b.Property<bool?>("UsesMedication")
                        .HasColumnType("boolean")
                        .HasColumnName("uses_medication");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId")
                        .IsUnique();

                    b.HasIndex("SignedByProfessionalId");

                    b.ToTable("pre_anesthesia_records", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("PreAnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("pre_anesthesia_record_id");

                    b.Property<int?>("Specialty")
                        .HasColumnType("integer")
                        .HasColumnName("specialty");

                    b.HasKey("Id");

                    b.HasIndex("PreAnesthesiaRecordId");

                    b.ToTable("pre_anesthesia_reports", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaSurgery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PreAnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("pre_anesthesia_record_id");

                    b.HasKey("Id");

                    b.HasIndex("PreAnesthesiaRecordId");

                    b.ToTable("pre_anesthesia_surgeries", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Cid")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("procedures", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanLogIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_login");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<DateTime?>("LastLoginAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<int>("MedicalSpecialty")
                        .HasColumnType("integer")
                        .HasColumnName("medical_specialty");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("password");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("registration");

                    b.Property<string>("Sector")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sector");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CanLogIn");

                    b.HasIndex("Email");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("users", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("pt-BR")
                        .HasColumnName("language");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("monitoring_interval_minutes");

                    b.Property<bool>("UseInstitutionalInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("use_institutional_interval");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_settings", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Bis")
                        .HasColumnType("integer")
                        .HasColumnName("bis");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<int?>("DiastolicBloodPressure")
                        .HasColumnType("integer")
                        .HasColumnName("diastolic_blood_pressure");

                    b.Property<int?>("Etco2")
                        .HasColumnType("integer")
                        .HasColumnName("etco2");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int?>("MeanArterialPressure")
                        .HasColumnType("integer")
                        .HasColumnName("mean_arterial_pressure");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<decimal?>("Pcap")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("pcap");

                    b.Property<decimal?>("Pvc")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("pvc");

                    b.Property<int?>("Spo2")
                        .HasColumnType("integer")
                        .HasColumnName("spo2");

                    b.Property<int?>("SystolicBloodPressure")
                        .HasColumnType("integer")
                        .HasColumnName("systolic_blood_pressure");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("MonitoringRecordId");

                    b.ToTable("vital_sign_records", "siga_db");
                });

            modelBuilder.Entity("AdministeredAgent", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_administered_agents__drugs_drug_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany("AdministeredAgents")
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_administered_agents__monitoring_records_monitoring_record_id");

                    b.Navigation("Drug");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("AnesthesiaRecordSurgery", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("Surgeries")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_procedures__anesthesia_records_anesthesia_r~");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.Procedure", "Procedure")
                        .WithMany("AnesthesiaRecords")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_procedures__procedures_procedure_id");

                    b.Navigation("AnesthesiaRecord");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "Assistant")
                        .WithMany()
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_records__users_assistant_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "FirstAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("FirstAnesthesiologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_records__users_first_anesthesiologist_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "SecondAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("SecondAnesthesiologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_records__users_second_anesthesiologist_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "Surgeon")
                        .WithMany()
                        .HasForeignKey("SurgeonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_records__users_surgeon_id");

                    b.Navigation("Assistant");

                    b.Navigation("FirstAnesthesiologist");

                    b.Navigation("SecondAnesthesiologist");

                    b.Navigation("Surgeon");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAirwayDevice", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("AirwayDevices")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_airway_devices_anesthesia_records_anesthe~");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibiotic", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("Antibiotics")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_antibiotic_anesthesia_records_anesthesia_~");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibioticBooster", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibiotic", "Antibiotic")
                        .WithMany("Boosters")
                        .HasForeignKey("AnesthesiaRecordAntibioticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_antibiotic_booster_anesthesia_record_anti~");

                    b.Navigation("Antibiotic");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordOxygenSupplementation", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("OxygenSupplementationTypes")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_oxygen_supplementations_anesthesia_record~");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordPunctureLevel", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("PunctureLevels")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_puncture_levels_anesthesia_records_anesth~");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordStimulatedNerve", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("StimulatedNerves")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_stimulated_nerves_anesthesia_records_anes~");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.ClinicalEvent", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany("ClinicalEvents")
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_clinical_events__monitoring_records_monitoring_record_id");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.CustomField", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", null)
                        .WithMany("CustomFields")
                        .HasForeignKey("vital_sign_record_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_custom_fields__vital_sign_records_vital_sign_record_id");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.FluidBalance", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany("FluidBalances")
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fluid_balances__monitoring_records_monitoring_record_id");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.InstitutionSettings", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithOne("MonitoringRecord")
                        .HasForeignKey("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_monitoring_records_anesthesia_records_anesthesia_record_id");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PatientPosition", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany("Positions")
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_patient_position_monitoring_records_monitoring_record_id");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaComorbidity", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", "PreAnesthesiaRecord")
                        .WithMany("Comorbidities")
                        .HasForeignKey("PreAnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pre_anesthesia_comorbidities_pre_anesthesia_record");

                    b.Navigation("PreAnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaMedication", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", "PreAnesthesiaRecord")
                        .WithMany("Medications")
                        .HasForeignKey("PreAnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pre_anesthesia_medications_pre_anesthesia_record");

                    b.Navigation("PreAnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaPhysicalExamArea", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", "PreAnesthesiaRecord")
                        .WithMany("PhysicalExamAreas")
                        .HasForeignKey("PreAnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pre_anesthesia_physical_exam_areas_pre_anesthesia_record");

                    b.Navigation("PreAnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany()
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pre_anesthesia_records_anesthesia_record");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "SignedByProfessional")
                        .WithMany()
                        .HasForeignKey("SignedByProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pre_anesthesia_records_signed_by_professional");

                    b.Navigation("AnesthesiaRecord");

                    b.Navigation("SignedByProfessional");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaReport", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", "PreAnesthesiaRecord")
                        .WithMany("Reports")
                        .HasForeignKey("PreAnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pre_anesthesia_reports_pre_anesthesia_record");

                    b.Navigation("PreAnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaSurgery", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", "PreAnesthesiaRecord")
                        .WithMany("Surgeries")
                        .HasForeignKey("PreAnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pre_anesthesia_surgeries_pre_anesthesia_record");

                    b.Navigation("PreAnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_settings_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany("VitalSigns")
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_vital_sign_records_monitoring_records_monitoring_record_id");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", b =>
                {
                    b.Navigation("AirwayDevices");

                    b.Navigation("Antibiotics");

                    b.Navigation("MonitoringRecord");

                    b.Navigation("OxygenSupplementationTypes");

                    b.Navigation("PunctureLevels");

                    b.Navigation("StimulatedNerves");

                    b.Navigation("Surgeries");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibiotic", b =>
                {
                    b.Navigation("Boosters");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", b =>
                {
                    b.Navigation("AdministeredAgents");

                    b.Navigation("ClinicalEvents");

                    b.Navigation("FluidBalances");

                    b.Navigation("Positions");

                    b.Navigation("VitalSigns");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", b =>
                {
                    b.Navigation("Comorbidities");

                    b.Navigation("Medications");

                    b.Navigation("PhysicalExamAreas");

                    b.Navigation("Reports");

                    b.Navigation("Surgeries");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Procedure", b =>
                {
                    b.Navigation("AnesthesiaRecords");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", b =>
                {
                    b.Navigation("CustomFields");
                });
#pragma warning restore 612, 618
        }
    }
}
