// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UFF.FichaAnestesica.Infra.Context;

#nullable disable

namespace UFF.FichaAnestesica.Infra.Migrations
{
    [DbContext(typeof(SigaDbCtx))]
    [Migration("20260523180833_Adiciona tabelas base")]
    partial class Adicionatabelasbase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("siga_db")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProcedureSurgery", b =>
                {
                    b.Property<int>("ProceduresId")
                        .HasColumnType("integer");

                    b.Property<int>("SurgeryId")
                        .HasColumnType("integer");

                    b.HasKey("ProceduresId", "SurgeryId");

                    b.HasIndex("SurgeryId");

                    b.ToTable("surgery_procedures", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.CurrentLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bed")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("bed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("floor");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("room");

                    b.Property<int?>("patient_id")
                        .HasColumnType("integer");

                    b.Property<int>("unit_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("patient_id")
                        .IsUnique();

                    b.HasIndex("unit_id");

                    b.ToTable("current_locations", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalIdHuap")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id_huap");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("gender");

                    b.Property<int>("HeightCm")
                        .HasColumnType("integer")
                        .HasColumnName("height_cm");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("medical_record_number");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("patient_id");

                    b.Property<double>("WeightKg")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.ToTable("patients", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cid")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("procedure_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("procedures", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("specialties", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Surgery", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SurgeryDate")
                        .HasColumnType("date")
                        .HasColumnName("surgery_date");

                    b.Property<string>("SurgeryId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("surgery_id");

                    b.Property<int>("patient_id")
                        .HasColumnType("integer");

                    b.Property<int>("specialty_id")
                        .HasColumnType("integer");

                    b.Property<int>("surgery_location_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("specialty_id");

                    b.HasIndex("surgery_location_id");

                    b.ToTable("surgeries", "siga_db", t =>
                        {
                            t.Property("patient_id")
                                .HasColumnName("patient_id1");
                        });
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.SurgeryLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("room");

                    b.Property<int>("surgical_center_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("surgical_center_id");

                    b.ToTable("surgery_locations", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.SurgicalCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("surgical_centers", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("units", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanLogIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_login");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("registration");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("role");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sector");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CanLogIn");

                    b.HasIndex("Email");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("users", "siga_db");
                });

            modelBuilder.Entity("ProcedureSurgery", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.Procedure", null)
                        .WithMany()
                        .HasForeignKey("ProceduresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.Surgery", null)
                        .WithMany()
                        .HasForeignKey("SurgeryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.CurrentLocation", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.Patient", null)
                        .WithOne("CurrentLocation")
                        .HasForeignKey("UFF.FichaAnestesica.Domain.Entities.CurrentLocation", "patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_patients_current_locations_current_location_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("unit_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_current_locations__units_unit_id");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Surgery", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.Patient", "Patient")
                        .WithMany("Surgeries")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_surgeries_patients_patient_id1");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("specialty_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_surgeries_specialties_specialty_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.SurgeryLocation", "Location")
                        .WithMany()
                        .HasForeignKey("surgery_location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_surgeries__surgery_locations_location_id");

                    b.Navigation("Location");

                    b.Navigation("Patient");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.SurgeryLocation", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.SurgicalCenter", "SurgicalCenter")
                        .WithMany()
                        .HasForeignKey("surgical_center_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_surgery_locations__surgical_centers_surgical_center_id");

                    b.Navigation("SurgicalCenter");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Patient", b =>
                {
                    b.Navigation("CurrentLocation")
                        .IsRequired();

                    b.Navigation("Surgeries");
                });
#pragma warning restore 612, 618
        }
    }
}
