// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UFF.FichaAnestesica.Infra.Context;

#nullable disable

namespace UFF.FichaAnestesica.Infra.Migrations
{
    [DbContext(typeof(SigaDbCtx))]
    [Migration("20260529162737_hangfire")]
    partial class hangfire
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("siga_db")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdministeredAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Dose")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("dose");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer")
                        .HasColumnName("drug_id");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<string>("Presentation")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("presentation");

                    b.Property<int>("Route")
                        .HasColumnType("integer")
                        .HasColumnName("route");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<int>("Unit")
                        .HasColumnType("integer")
                        .HasColumnName("unit");

                    b.Property<int>("monitoring_record_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.HasIndex("MonitoringRecordId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("monitoring_record_id");

                    b.ToTable("administered_agents", "siga_db", t =>
                        {
                            t.Property("monitoring_record_id")
                                .HasColumnName("monitoring_record_id1");
                        });
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("activity_score");

                    b.Property<string>("AirwayDeviceNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("airway_device_number");

                    b.Property<int?>("AirwayDeviceType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_device_type");

                    b.Property<int?>("AirwayType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_type");

                    b.Property<TimeOnly>("AnesthesiaEndTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_end_time");

                    b.Property<bool>("AnesthesiaEquipmentChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthesia_equipment_checked");

                    b.Property<TimeOnly>("AnesthesiaStartTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_start_time");

                    b.Property<bool>("AnestheticConsentSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthetic_consent_signed");

                    b.Property<int>("AsaClassification")
                        .HasColumnType("integer")
                        .HasColumnName("asa_classification");

                    b.Property<string>("Assistant")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("assistant");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<bool>("Bronchofibroscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("bronchofibroscopy");

                    b.Property<int>("CirculationScore")
                        .HasColumnType("integer")
                        .HasColumnName("circulation_score");

                    b.Property<int>("ClinicalDischargeCondition")
                        .HasColumnType("integer")
                        .HasColumnName("clinical_discharge_condition");

                    b.Property<bool>("Co2AbsorberCircuit")
                        .HasColumnType("boolean")
                        .HasColumnName("co2_absorber_circuit");

                    b.Property<int>("ConsciousnessScore")
                        .HasColumnType("integer")
                        .HasColumnName("consciousness_score");

                    b.Property<int?>("ControlledVentilationMode")
                        .HasColumnType("integer")
                        .HasColumnName("controlled_ventilation_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("Destination")
                        .HasColumnType("integer")
                        .HasColumnName("destination");

                    b.Property<bool>("DifficultVenousPuncture")
                        .HasColumnType("boolean")
                        .HasColumnName("difficult_venous_puncture");

                    b.Property<string>("ExternalPatientId")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("patient_id");

                    b.Property<int?>("FirstAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("first_anesthesiologist_id");

                    b.Property<bool>("GeneralAnesthesia")
                        .HasColumnType("boolean")
                        .HasColumnName("general_anesthesia");

                    b.Property<bool>("HasPain")
                        .HasColumnType("boolean")
                        .HasColumnName("has_pain");

                    b.Property<int?>("IntubationDifficulty")
                        .HasColumnType("integer")
                        .HasColumnName("intubation_difficulty");

                    b.Property<bool>("Laryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("laryngoscopy");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<bool>("NasalTube")
                        .HasColumnType("boolean")
                        .HasColumnName("nasal_tube");

                    b.Property<bool>("OralTube")
                        .HasColumnType("boolean")
                        .HasColumnName("oral_tube");

                    b.Property<string>("OtherAirwayTechnique")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_technique");

                    b.Property<string>("OtherAirwayTypeDescription")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_type_description");

                    b.Property<int>("OxygenSaturation")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation");

                    b.Property<int>("OxygenSaturationScore")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation_score");

                    b.Property<bool>("OxygenSupplementation")
                        .HasColumnType("boolean")
                        .HasColumnName("oxygen_supplementation");

                    b.Property<bool>("PatientIdentifiedBeforeInduction")
                        .HasColumnType("boolean")
                        .HasColumnName("patient_identified_before_induction");

                    b.Property<bool>("PlexusBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("plexus_block_performed");

                    b.Property<string>("PostOperativeDiagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_operative_diagnosis");

                    b.Property<bool>("PreAnestheticMedication")
                        .HasColumnType("boolean")
                        .HasColumnName("pre_anesthetic_medication");

                    b.Property<string>("PreOperativeDiagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pre_operative_diagnosis");

                    b.Property<bool>("ProphylacticAntibioticUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("prophylactic_antibiotic_used");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("RespirationMode")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_mode");

                    b.Property<int>("RespirationScore")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_score");

                    b.Property<int>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<bool>("RetrogradeTechnique")
                        .HasColumnType("boolean")
                        .HasColumnName("retrograde_technique");

                    b.Property<TimeOnly>("RoomEntryTime")
                        .HasColumnType("time")
                        .HasColumnName("room_entry_time");

                    b.Property<string>("SafetyObservations")
                        .HasColumnType("text")
                        .HasColumnName("safety_observations");

                    b.Property<int?>("SecondAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("second_anesthesiologist_id");

                    b.Property<bool>("SedationPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("sedation_performed");

                    b.Property<bool>("SpinalBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("spinal_block_performed");

                    b.Property<string>("Surgeon")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("surgeon");

                    b.Property<TimeOnly>("SurgeryEndTime")
                        .HasColumnType("time")
                        .HasColumnName("surgery_end_time");

                    b.Property<string>("SurgeryPerformed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surgery_performed");

                    b.Property<int>("SurgicalPosition")
                        .HasColumnType("integer")
                        .HasColumnName("surgical_position");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<int>("TotalAldreteKroulikScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_aldrete_kroulik_score");

                    b.Property<bool>("Tracheostomy")
                        .HasColumnType("boolean")
                        .HasColumnName("tracheostomy");

                    b.Property<bool>("UsesCushions")
                        .HasColumnType("boolean")
                        .HasColumnName("uses_cushions");

                    b.Property<string>("VenousAccessLocation")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("venous_access_location");

                    b.Property<int>("VenousAccessType")
                        .HasColumnType("integer")
                        .HasColumnName("venous_access_type");

                    b.Property<bool>("VideoLaryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("video_laryngoscopy");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("FirstAnesthesiologistId");

                    b.HasIndex("SecondAnesthesiologistId");

                    b.ToTable("anesthesia_records", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.ClinicalEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<int>("monitoring_record_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("MonitoringRecordId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("monitoring_record_id");

                    b.ToTable("clinical_events", "siga_db", t =>
                        {
                            t.Property("monitoring_record_id")
                                .HasColumnName("monitoring_record_id1");
                        });
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.CustomField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("value");

                    b.Property<int?>("vital_sign_record_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("vital_sign_record_id");

                    b.ToTable("custom_fields", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultUnit")
                        .HasColumnType("integer")
                        .HasColumnName("default_unit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Presentation")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("default_presentation");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("drugs", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.FluidBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<decimal>("VolumeMl")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("volume_ml");

                    b.Property<int>("monitoring_record_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("MonitoringRecordId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.HasIndex("monitoring_record_id");

                    b.ToTable("fluid_balances", "siga_db", t =>
                        {
                            t.Property("monitoring_record_id")
                                .HasColumnName("monitoring_record_id1");
                        });
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("RecordedByProfessionalId")
                        .HasColumnType("integer")
                        .HasColumnName("recorded_by_professional_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<int>("SurgeryId")
                        .HasColumnType("integer")
                        .HasColumnName("surgery_id");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId");

                    b.HasIndex("RecordedByProfessionalId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("SurgeryId");

                    b.ToTable("monitoring_records", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("activity_score");

                    b.Property<string>("AirwayDeviceNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("airway_device_number");

                    b.Property<int?>("AirwayDeviceType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_device_type");

                    b.Property<int?>("AirwayType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_type");

                    b.Property<TimeOnly>("AnesthesiaEndTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_end_time");

                    b.Property<bool>("AnesthesiaEquipmentChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthesia_equipment_checked");

                    b.Property<TimeOnly>("AnesthesiaStartTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_start_time");

                    b.Property<bool>("AnestheticConsentSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthetic_consent_signed");

                    b.Property<int>("AsaClassification")
                        .HasColumnType("integer")
                        .HasColumnName("asa_classification");

                    b.Property<string>("Assistant")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("assistant");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<bool>("Bronchofibroscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("bronchofibroscopy");

                    b.Property<int>("CirculationScore")
                        .HasColumnType("integer")
                        .HasColumnName("circulation_score");

                    b.Property<int>("ClinicalDischargeCondition")
                        .HasColumnType("integer")
                        .HasColumnName("clinical_discharge_condition");

                    b.Property<bool>("Co2AbsorberCircuit")
                        .HasColumnType("boolean")
                        .HasColumnName("co2_absorber_circuit");

                    b.Property<int>("ConsciousnessScore")
                        .HasColumnType("integer")
                        .HasColumnName("consciousness_score");

                    b.Property<int?>("ControlledVentilationMode")
                        .HasColumnType("integer")
                        .HasColumnName("controlled_ventilation_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("Destination")
                        .HasColumnType("integer")
                        .HasColumnName("destination");

                    b.Property<bool>("DifficultVenousPuncture")
                        .HasColumnType("boolean")
                        .HasColumnName("difficult_venous_puncture");

                    b.Property<int>("FirstAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("first_anesthesiologist_id");

                    b.Property<bool>("GeneralAnesthesia")
                        .HasColumnType("boolean")
                        .HasColumnName("general_anesthesia");

                    b.Property<bool>("HasPain")
                        .HasColumnType("boolean")
                        .HasColumnName("has_pain");

                    b.Property<int?>("IntubationDifficulty")
                        .HasColumnType("integer")
                        .HasColumnName("intubation_difficulty");

                    b.Property<bool>("Laryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("laryngoscopy");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<bool>("NasalTube")
                        .HasColumnType("boolean")
                        .HasColumnName("nasal_tube");

                    b.Property<bool>("OralTube")
                        .HasColumnType("boolean")
                        .HasColumnName("oral_tube");

                    b.Property<string>("OtherAirwayTechnique")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_technique");

                    b.Property<string>("OtherAirwayTypeDescription")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_type_description");

                    b.Property<int>("OxygenSaturation")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation");

                    b.Property<int>("OxygenSaturationScore")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation_score");

                    b.Property<bool>("OxygenSupplementation")
                        .HasColumnType("boolean")
                        .HasColumnName("oxygen_supplementation");

                    b.Property<bool>("PatientIdentifiedBeforeInduction")
                        .HasColumnType("boolean")
                        .HasColumnName("patient_identified_before_induction");

                    b.Property<bool>("PlexusBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("plexus_block_performed");

                    b.Property<string>("PostOperativeDiagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_operative_diagnosis");

                    b.Property<bool>("PreAnestheticMedication")
                        .HasColumnType("boolean")
                        .HasColumnName("pre_anesthetic_medication");

                    b.Property<string>("PreOperativeDiagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pre_operative_diagnosis");

                    b.Property<bool>("ProphylacticAntibioticUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("prophylactic_antibiotic_used");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("RespirationMode")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_mode");

                    b.Property<int>("RespirationScore")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_score");

                    b.Property<int>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<bool>("RetrogradeTechnique")
                        .HasColumnType("boolean")
                        .HasColumnName("retrograde_technique");

                    b.Property<TimeOnly>("RoomEntryTime")
                        .HasColumnType("time")
                        .HasColumnName("room_entry_time");

                    b.Property<string>("SafetyObservations")
                        .HasColumnType("text")
                        .HasColumnName("safety_observations");

                    b.Property<int>("SecondAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("second_anesthesiologist_id");

                    b.Property<bool>("SedationPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("sedation_performed");

                    b.Property<bool>("SpinalBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("spinal_block_performed");

                    b.Property<string>("Surgeon")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("surgeon");

                    b.Property<TimeOnly>("SurgeryEndTime")
                        .HasColumnType("time")
                        .HasColumnName("surgery_end_time");

                    b.Property<string>("SurgeryPerformed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surgery_performed");

                    b.Property<int>("SurgicalPosition")
                        .HasColumnType("integer")
                        .HasColumnName("surgical_position");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<int>("TotalAldreteKroulikScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_aldrete_kroulik_score");

                    b.Property<bool>("Tracheostomy")
                        .HasColumnType("boolean")
                        .HasColumnName("tracheostomy");

                    b.Property<bool>("UsesCushions")
                        .HasColumnType("boolean")
                        .HasColumnName("uses_cushions");

                    b.Property<string>("VenousAccessLocation")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("venous_access_location");

                    b.Property<int>("VenousAccessType")
                        .HasColumnType("integer")
                        .HasColumnName("venous_access_type");

                    b.Property<bool>("VideoLaryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("video_laryngoscopy");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.Property<int>("first_anesthesiologist_id")
                        .HasColumnType("integer");

                    b.Property<int>("second_anesthesiologist_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("first_anesthesiologist_id");

                    b.HasIndex("second_anesthesiologist_id");

                    b.ToTable("pre_anesthesia_records", "siga_db", t =>
                        {
                            t.Property("first_anesthesiologist_id")
                                .HasColumnName("first_anesthesiologist_id1");

                            t.Property("second_anesthesiologist_id")
                                .HasColumnName("second_anesthesiologist_id1");
                        });
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanLogIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_login");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("LastLoginAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("registration");

                    b.Property<string>("Sector")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sector");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CanLogIn");

                    b.HasIndex("Email");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("users", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Bis")
                        .HasColumnType("integer")
                        .HasColumnName("bis");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int?>("DiastolicBloodPressure")
                        .HasColumnType("integer")
                        .HasColumnName("diastolic_blood_pressure");

                    b.Property<int?>("Etco2")
                        .HasColumnType("integer")
                        .HasColumnName("etco2");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int?>("MeanArterialPressure")
                        .HasColumnType("integer")
                        .HasColumnName("mean_arterial_pressure");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<decimal?>("Pcap")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("pcap");

                    b.Property<decimal?>("Pvc")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("pvc");

                    b.Property<int?>("Spo2")
                        .HasColumnType("integer")
                        .HasColumnName("spo2");

                    b.Property<int?>("SystolicBloodPressure")
                        .HasColumnType("integer")
                        .HasColumnName("systolic_blood_pressure");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<int>("monitoring_record_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MonitoringRecordId");

                    b.HasIndex("Timestamp");

                    b.ToTable("vital_sign_records", "siga_db", t =>
                        {
                            t.Property("monitoring_record_id")
                                .HasColumnName("monitoring_record_id1");
                        });
                });

            modelBuilder.Entity("AdministeredAgent", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_administered_agents__drugs_drug_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany()
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", null)
                        .WithMany("AdministeredAgents")
                        .HasForeignKey("monitoring_record_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_administered_agents__monitoring_records_monitoring_record_id");

                    b.Navigation("Drug");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "FirstAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("FirstAnesthesiologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_records__users_first_anesthesiologist_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "SecondAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("SecondAnesthesiologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_records__users_second_anesthesiologist_id");

                    b.Navigation("FirstAnesthesiologist");

                    b.Navigation("SecondAnesthesiologist");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.ClinicalEvent", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany()
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", null)
                        .WithMany("ClinicalEvents")
                        .HasForeignKey("monitoring_record_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_clinical_events__monitoring_records_monitoring_record_id");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.CustomField", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", null)
                        .WithMany("CustomFields")
                        .HasForeignKey("vital_sign_record_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_custom_fields__vital_sign_records_vital_sign_record_id");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.FluidBalance", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany()
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", null)
                        .WithMany("FluidBalances")
                        .HasForeignKey("monitoring_record_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fluid_balances__monitoring_records_monitoring_record_id");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "FirstAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("first_anesthesiologist_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_pre_anesthesia_records__users_first_anesthesiologist_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "SecondAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("second_anesthesiologist_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_pre_anesthesia_records__users_second_anesthesiologist_id");

                    b.Navigation("FirstAnesthesiologist");

                    b.Navigation("SecondAnesthesiologist");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany("VitalSigns")
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_vital_sign_records_monitoring_records_monitoring_record_id");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", b =>
                {
                    b.Navigation("AdministeredAgents");

                    b.Navigation("ClinicalEvents");

                    b.Navigation("FluidBalances");

                    b.Navigation("VitalSigns");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", b =>
                {
                    b.Navigation("CustomFields");
                });
#pragma warning restore 612, 618
        }
    }
}
