// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UFF.FichaAnestesica.Infra.Context;

#nullable disable

namespace UFF.FichaAnestesica.Infra.Migrations
{
    [DbContext(typeof(SigaDbCtx))]
    [Migration("20260816154917_ajusta campos do monitoramento")]
    partial class ajustacamposdomonitoramento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("siga_db")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdministeredAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal>("Dose")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("dose");

                    b.Property<int>("DrugId")
                        .HasColumnType("integer")
                        .HasColumnName("drug_id");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<int>("Route")
                        .HasColumnType("integer")
                        .HasColumnName("route");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("DrugId");

                    b.HasIndex("MonitoringRecordId");

                    b.ToTable("administered_agents", "siga_db");
                });

            modelBuilder.Entity("AnesthesiaRecordSurgery", b =>
                {
                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("integer")
                        .HasColumnName("procedure_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.HasKey("AnesthesiaRecordId", "ProcedureId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("anesthesia_record_procedures", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("ActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("activity_score");

                    b.Property<string>("AirwayDeviceNumbers")
                        .HasColumnType("jsonb")
                        .HasColumnName("airway_device_numbers");

                    b.Property<int?>("AirwayType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_type");

                    b.Property<TimeOnly?>("AldreteEvaluationTime")
                        .HasColumnType("time")
                        .HasColumnName("aldrete_evaluation_time");

                    b.Property<TimeOnly?>("AnesthesiaEndTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_end_time");

                    b.Property<bool?>("AnesthesiaEquipmentChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthesia_equipment_checked");

                    b.Property<TimeOnly?>("AnesthesiaStartTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_start_time");

                    b.Property<bool?>("AnestheticConsentSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthetic_consent_signed");

                    b.Property<int?>("AsaClassification")
                        .HasColumnType("integer")
                        .HasColumnName("asa_classification");

                    b.Property<int?>("AssistantId")
                        .HasColumnType("integer")
                        .HasColumnName("assistant_id");

                    b.Property<string>("BloodPressure")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<bool?>("Bronchofibroscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("bronchofibroscopy");

                    b.Property<int?>("CirculationScore")
                        .HasColumnType("integer")
                        .HasColumnName("circulation_score");

                    b.Property<int?>("ClinicalDischargeCondition")
                        .HasColumnType("integer")
                        .HasColumnName("clinical_discharge_condition");

                    b.Property<bool?>("Co2AbsorberCircuit")
                        .HasColumnType("boolean")
                        .HasColumnName("co2_absorber_circuit");

                    b.Property<string>("Conduta")
                        .HasColumnType("text")
                        .HasColumnName("conduta");

                    b.Property<int?>("ConsciousnessScore")
                        .HasColumnType("integer")
                        .HasColumnName("consciousness_score");

                    b.Property<int?>("ControlledVentilationMode")
                        .HasColumnType("integer")
                        .HasColumnName("controlled_ventilation_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool?>("Cuff")
                        .HasColumnType("boolean")
                        .HasColumnName("cuff");

                    b.Property<string>("CushionsAccessLocation")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cushions_access_location");

                    b.Property<int?>("Destination")
                        .HasColumnType("integer")
                        .HasColumnName("destination");

                    b.Property<bool?>("DifficultVenousPuncture")
                        .HasColumnType("boolean")
                        .HasColumnName("difficult_venous_puncture");

                    b.Property<string>("DischargeConditionOther")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("discharge_condition_other");

                    b.Property<int?>("DorBPS")
                        .HasColumnType("integer")
                        .HasColumnName("dor_bps");

                    b.Property<int?>("DorENV")
                        .HasColumnType("integer")
                        .HasColumnName("dor_env");

                    b.Property<int?>("DorPAINAD")
                        .HasColumnType("integer")
                        .HasColumnName("dor_painad");

                    b.Property<bool?>("DorUsouBPS")
                        .HasColumnType("boolean")
                        .HasColumnName("dor_usou_bps");

                    b.Property<bool?>("DorUsouENV")
                        .HasColumnType("boolean")
                        .HasColumnName("dor_usou_env");

                    b.Property<bool?>("DorUsouPAINAD")
                        .HasColumnType("boolean")
                        .HasColumnName("dor_usou_painad");

                    b.Property<int?>("FirstAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("first_anesthesiologist_id");

                    b.Property<bool?>("GeneralAnesthesia")
                        .HasColumnType("boolean")
                        .HasColumnName("general_anesthesia");

                    b.Property<bool?>("HasOtherAirwayTechnique")
                        .HasColumnType("boolean")
                        .HasColumnName("has_other_airway_technique");

                    b.Property<bool?>("HasOxygenSupplementationOther")
                        .HasColumnType("boolean")
                        .HasColumnName("has_oxygen_supplementation_other");

                    b.Property<bool?>("HasPain")
                        .HasColumnType("boolean")
                        .HasColumnName("has_pain");

                    b.Property<int?>("IntubationDifficulty")
                        .HasColumnType("integer")
                        .HasColumnName("intubation_difficulty");

                    b.Property<bool?>("Iot")
                        .HasColumnType("boolean")
                        .HasColumnName("iot");

                    b.Property<bool?>("Laryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("laryngoscopy");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<bool?>("NasalTube")
                        .HasColumnType("boolean")
                        .HasColumnName("nasal_tube");

                    b.Property<bool?>("NeurostimulatorUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("neurostimulator_used");

                    b.Property<bool?>("OralTube")
                        .HasColumnType("boolean")
                        .HasColumnName("oral_tube");

                    b.Property<string>("OtherAirwayTechnique")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_technique");

                    b.Property<string>("OtherAirwayTypeDescription")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_type_description");

                    b.Property<string>("OtherSurgicalPosition")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_surgical_position");

                    b.Property<string>("OtherVenousAccess")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("other_venous_access");

                    b.Property<int?>("OxygenSaturation")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation");

                    b.Property<int?>("OxygenSaturationScore")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation_score");

                    b.Property<bool?>("OxygenSupplementation")
                        .HasColumnType("boolean")
                        .HasColumnName("oxygen_supplementation");

                    b.Property<string>("OxygenSupplementationOther")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("oxygen_supplementation_other");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("patient_id");

                    b.Property<bool?>("PatientIdentifiedBeforeInduction")
                        .HasColumnType("boolean")
                        .HasColumnName("patient_identified_before_induction");

                    b.Property<bool?>("PlexusBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("plexus_block_performed");

                    b.Property<string>("PostOperativeDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("post_operative_diagnosis");

                    b.Property<bool?>("PreAnestheticMedication")
                        .HasColumnType("boolean")
                        .HasColumnName("pre_anesthetic_medication");

                    b.Property<string>("PreAnestheticMedicationDose")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pre_anesthetic_medication_dose");

                    b.Property<int?>("PreAnestheticMedicationId")
                        .HasColumnType("integer")
                        .HasColumnName("pre_anesthetic_medication_id");

                    b.Property<string>("PreAnestheticMedicationName")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("pre_anesthetic_medication_name");

                    b.Property<string>("PreAnestheticMedicationOtherRoute")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pre_anesthetic_medication_other_route");

                    b.Property<string>("PreAnestheticMedicationRoute")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pre_anesthetic_medication_route");

                    b.Property<TimeOnly?>("PreAnestheticMedicationTime")
                        .HasColumnType("time")
                        .HasColumnName("pre_anesthetic_medication_time");

                    b.Property<string>("PreOperativeDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("pre_operative_diagnosis");

                    b.Property<bool>("ProceduresCustomized")
                        .HasColumnType("boolean")
                        .HasColumnName("procedures_customized");

                    b.Property<bool?>("ProphylacticAntibioticUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("prophylactic_antibiotic_used");

                    b.Property<int?>("PunctureCount")
                        .HasColumnType("integer")
                        .HasColumnName("puncture_count");

                    b.Property<int?>("PuncturePosition")
                        .HasColumnType("integer")
                        .HasColumnName("puncture_position");

                    b.Property<int?>("RespirationMode")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_mode");

                    b.Property<int?>("RespirationScore")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_score");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<bool?>("RetrogradeTechnique")
                        .HasColumnType("boolean")
                        .HasColumnName("retrograde_technique");

                    b.Property<TimeOnly?>("RoomEntryTime")
                        .HasColumnType("time")
                        .HasColumnName("room_entry_time");

                    b.Property<string>("SafetyObservations")
                        .HasColumnType("text")
                        .HasColumnName("safety_observations");

                    b.Property<int?>("SecondAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("second_anesthesiologist_id");

                    b.Property<bool?>("SedationPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("sedation_performed");

                    b.Property<DateTime?>("SignatureDate")
                        .HasColumnType("date")
                        .HasColumnName("signature_date");

                    b.Property<bool?>("SpinalBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("spinal_block_performed");

                    b.Property<bool?>("SpinalCatheter")
                        .HasColumnType("boolean")
                        .HasColumnName("spinal_catheter");

                    b.Property<bool?>("SpinalOpioid")
                        .HasColumnType("boolean")
                        .HasColumnName("spinal_opioid");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("SurgeonId")
                        .HasColumnType("integer")
                        .HasColumnName("surgeon_id");

                    b.Property<DateTime>("SurgeryDate")
                        .HasColumnType("date")
                        .HasColumnName("surgery_date");

                    b.Property<TimeOnly?>("SurgeryEndTime")
                        .HasColumnType("time")
                        .HasColumnName("surgery_end_time");

                    b.Property<string>("SurgeryPerformed")
                        .HasColumnType("text")
                        .HasColumnName("surgery_performed");

                    b.Property<int?>("SurgicalPosition")
                        .HasColumnType("integer")
                        .HasColumnName("surgical_position");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<int?>("TotalAldreteKroulikScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_aldrete_kroulik_score");

                    b.Property<bool?>("Tracheostomy")
                        .HasColumnType("boolean")
                        .HasColumnName("tracheostomy");

                    b.Property<bool?>("UsesCushions")
                        .HasColumnType("boolean")
                        .HasColumnName("uses_cushions");

                    b.Property<string>("VenousAccessLocation")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("venous_access_location");

                    b.Property<int?>("VenousAccessType")
                        .HasColumnType("integer")
                        .HasColumnName("venous_access_type");

                    b.Property<bool?>("VideoLaryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("video_laryngoscopy");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("AssistantId");

                    b.HasIndex("FirstAnesthesiologistId");

                    b.HasIndex("SecondAnesthesiologistId");

                    b.HasIndex("SurgeonId");

                    b.ToTable("anesthesia_records", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAirwayDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<int>("DeviceType")
                        .HasColumnType("integer")
                        .HasColumnName("device_type");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId");

                    b.ToTable("anesthesia_record_airway_devices", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibiotic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dose");

                    b.Property<bool>("HasBooster")
                        .HasColumnType("boolean")
                        .HasColumnName("has_booster");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer")
                        .HasColumnName("medication_id");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("medication_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("route");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId");

                    b.ToTable("anesthesia_record_antibiotics", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibioticBooster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordAntibioticId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_antibiotic_id");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dose");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer")
                        .HasColumnName("medication_id");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("medication_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("route");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordAntibioticId");

                    b.ToTable("anesthesia_record_antibiotic_boosters", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordOxygenSupplementation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId");

                    b.ToTable("anesthesia_record_oxygen_supplementations", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordPunctureLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId");

                    b.ToTable("anesthesia_record_puncture_levels", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordStimulatedNerve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<int>("Nerve")
                        .HasColumnType("integer")
                        .HasColumnName("nerve");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId");

                    b.ToTable("anesthesia_record_stimulated_nerves", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.ClinicalEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EventType");

                    b.HasIndex("MonitoringRecordId");

                    b.ToTable("clinical_events", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.CustomField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("value");

                    b.Property<int?>("vital_sign_record_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("vital_sign_record_id");

                    b.ToTable("custom_fields", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("default_unit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("drugs", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.FluidBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<decimal>("VolumeMl")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("volume_ml");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Date");

                    b.HasIndex("MonitoringRecordId");

                    b.HasIndex("Type");

                    b.ToTable("fluid_balances", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnesthesiaRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("anesthesia_record_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ended_at");

                    b.Property<bool>("IsMonitoringDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_monitoring_draft");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<DateTime?>("MonitoringUpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("monitoring_updated_at");

                    b.Property<int>("RecordedByProfessionalId")
                        .HasColumnType("integer")
                        .HasColumnName("recorded_by_professional_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SurgeryEndedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("surgery_ended_at");

                    b.Property<DateTime?>("SurgeryStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("surgery_started_at");

                    b.HasKey("Id");

                    b.HasIndex("AnesthesiaRecordId")
                        .IsUnique();

                    b.HasIndex("RecordedByProfessionalId");

                    b.HasIndex("StartedAt");

                    b.ToTable("monitoring_records", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PatientPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<int>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("MonitoringRecordId");

                    b.ToTable("patient_positions", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("activity_score");

                    b.Property<string>("AirwayDeviceNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("airway_device_number");

                    b.Property<int?>("AirwayDeviceType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_device_type");

                    b.Property<int?>("AirwayType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_type");

                    b.Property<TimeOnly>("AnesthesiaEndTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_end_time");

                    b.Property<bool>("AnesthesiaEquipmentChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthesia_equipment_checked");

                    b.Property<TimeOnly>("AnesthesiaStartTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_start_time");

                    b.Property<bool>("AnestheticConsentSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthetic_consent_signed");

                    b.Property<int>("AsaClassification")
                        .HasColumnType("integer")
                        .HasColumnName("asa_classification");

                    b.Property<string>("Assistant")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("assistant");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<bool>("Bronchofibroscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("bronchofibroscopy");

                    b.Property<int>("CirculationScore")
                        .HasColumnType("integer")
                        .HasColumnName("circulation_score");

                    b.Property<int>("ClinicalDischargeCondition")
                        .HasColumnType("integer")
                        .HasColumnName("clinical_discharge_condition");

                    b.Property<bool>("Co2AbsorberCircuit")
                        .HasColumnType("boolean")
                        .HasColumnName("co2_absorber_circuit");

                    b.Property<int>("ConsciousnessScore")
                        .HasColumnType("integer")
                        .HasColumnName("consciousness_score");

                    b.Property<int?>("ControlledVentilationMode")
                        .HasColumnType("integer")
                        .HasColumnName("controlled_ventilation_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("Destination")
                        .HasColumnType("integer")
                        .HasColumnName("destination");

                    b.Property<bool>("DifficultVenousPuncture")
                        .HasColumnType("boolean")
                        .HasColumnName("difficult_venous_puncture");

                    b.Property<int>("FirstAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("first_anesthesiologist_id");

                    b.Property<bool>("GeneralAnesthesia")
                        .HasColumnType("boolean")
                        .HasColumnName("general_anesthesia");

                    b.Property<bool>("HasPain")
                        .HasColumnType("boolean")
                        .HasColumnName("has_pain");

                    b.Property<int?>("IntubationDifficulty")
                        .HasColumnType("integer")
                        .HasColumnName("intubation_difficulty");

                    b.Property<bool>("Laryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("laryngoscopy");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<bool>("NasalTube")
                        .HasColumnType("boolean")
                        .HasColumnName("nasal_tube");

                    b.Property<bool>("OralTube")
                        .HasColumnType("boolean")
                        .HasColumnName("oral_tube");

                    b.Property<string>("OtherAirwayTechnique")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_technique");

                    b.Property<string>("OtherAirwayTypeDescription")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_type_description");

                    b.Property<int>("OxygenSaturation")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation");

                    b.Property<int>("OxygenSaturationScore")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation_score");

                    b.Property<bool>("OxygenSupplementation")
                        .HasColumnType("boolean")
                        .HasColumnName("oxygen_supplementation");

                    b.Property<bool>("PatientIdentifiedBeforeInduction")
                        .HasColumnType("boolean")
                        .HasColumnName("patient_identified_before_induction");

                    b.Property<bool>("PlexusBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("plexus_block_performed");

                    b.Property<string>("PostOperativeDiagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_operative_diagnosis");

                    b.Property<bool>("PreAnestheticMedication")
                        .HasColumnType("boolean")
                        .HasColumnName("pre_anesthetic_medication");

                    b.Property<string>("PreOperativeDiagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pre_operative_diagnosis");

                    b.Property<bool>("ProphylacticAntibioticUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("prophylactic_antibiotic_used");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("RespirationMode")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_mode");

                    b.Property<int>("RespirationScore")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_score");

                    b.Property<int>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<bool>("RetrogradeTechnique")
                        .HasColumnType("boolean")
                        .HasColumnName("retrograde_technique");

                    b.Property<TimeOnly>("RoomEntryTime")
                        .HasColumnType("time")
                        .HasColumnName("room_entry_time");

                    b.Property<string>("SafetyObservations")
                        .HasColumnType("text")
                        .HasColumnName("safety_observations");

                    b.Property<int>("SecondAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("second_anesthesiologist_id");

                    b.Property<bool>("SedationPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("sedation_performed");

                    b.Property<bool>("SpinalBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("spinal_block_performed");

                    b.Property<string>("Surgeon")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("surgeon");

                    b.Property<TimeOnly>("SurgeryEndTime")
                        .HasColumnType("time")
                        .HasColumnName("surgery_end_time");

                    b.Property<string>("SurgeryPerformed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surgery_performed");

                    b.Property<int>("SurgicalPosition")
                        .HasColumnType("integer")
                        .HasColumnName("surgical_position");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<int>("TotalAldreteKroulikScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_aldrete_kroulik_score");

                    b.Property<bool>("Tracheostomy")
                        .HasColumnType("boolean")
                        .HasColumnName("tracheostomy");

                    b.Property<bool>("UsesCushions")
                        .HasColumnType("boolean")
                        .HasColumnName("uses_cushions");

                    b.Property<string>("VenousAccessLocation")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("venous_access_location");

                    b.Property<int>("VenousAccessType")
                        .HasColumnType("integer")
                        .HasColumnName("venous_access_type");

                    b.Property<bool>("VideoLaryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("video_laryngoscopy");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.Property<int>("first_anesthesiologist_id")
                        .HasColumnType("integer");

                    b.Property<int>("second_anesthesiologist_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("first_anesthesiologist_id");

                    b.HasIndex("second_anesthesiologist_id");

                    b.ToTable("pre_anesthesia_records", "siga_db", t =>
                        {
                            t.Property("first_anesthesiologist_id")
                                .HasColumnName("first_anesthesiologist_id1");

                            t.Property("second_anesthesiologist_id")
                                .HasColumnName("second_anesthesiologist_id1");
                        });
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Cid")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("procedures", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanLogIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_login");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("LastLoginAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<int>("MedicalSpecialty")
                        .HasColumnType("integer")
                        .HasColumnName("medical_specialty");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("registration");

                    b.Property<string>("Sector")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sector");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CanLogIn");

                    b.HasIndex("Email");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("users", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Bis")
                        .HasColumnType("integer")
                        .HasColumnName("bis");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<int?>("DiastolicBloodPressure")
                        .HasColumnType("integer")
                        .HasColumnName("diastolic_blood_pressure");

                    b.Property<int?>("Etco2")
                        .HasColumnType("integer")
                        .HasColumnName("etco2");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<int?>("MeanArterialPressure")
                        .HasColumnType("integer")
                        .HasColumnName("mean_arterial_pressure");

                    b.Property<int>("MonitoringRecordId")
                        .HasColumnType("integer")
                        .HasColumnName("monitoring_record_id");

                    b.Property<decimal?>("Pcap")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("pcap");

                    b.Property<decimal?>("Pvc")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("pvc");

                    b.Property<int?>("Spo2")
                        .HasColumnType("integer")
                        .HasColumnName("spo2");

                    b.Property<int?>("SystolicBloodPressure")
                        .HasColumnType("integer")
                        .HasColumnName("systolic_blood_pressure");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("MonitoringRecordId");

                    b.ToTable("vital_sign_records", "siga_db");
                });

            modelBuilder.Entity("AdministeredAgent", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_administered_agents__drugs_drug_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany("AdministeredAgents")
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_administered_agents__monitoring_records_monitoring_record_id");

                    b.Navigation("Drug");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("AnesthesiaRecordSurgery", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("Surgeries")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_procedures__anesthesia_records_anesthesia_r~");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.Procedure", "Procedure")
                        .WithMany("AnesthesiaRecords")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_procedures__procedures_procedure_id");

                    b.Navigation("AnesthesiaRecord");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "Assistant")
                        .WithMany()
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_records__users_assistant_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "FirstAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("FirstAnesthesiologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_records__users_first_anesthesiologist_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "SecondAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("SecondAnesthesiologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_records__users_second_anesthesiologist_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "Surgeon")
                        .WithMany()
                        .HasForeignKey("SurgeonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_records__users_surgeon_id");

                    b.Navigation("Assistant");

                    b.Navigation("FirstAnesthesiologist");

                    b.Navigation("SecondAnesthesiologist");

                    b.Navigation("Surgeon");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAirwayDevice", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("AirwayDevices")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_airway_devices_anesthesia_records_anesthe~");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibiotic", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("Antibiotics")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_antibiotic_anesthesia_records_anesthesia_~");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibioticBooster", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibiotic", "Antibiotic")
                        .WithMany("Boosters")
                        .HasForeignKey("AnesthesiaRecordAntibioticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_antibiotic_booster_anesthesia_record_anti~");

                    b.Navigation("Antibiotic");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordOxygenSupplementation", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("OxygenSupplementationTypes")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_oxygen_supplementations_anesthesia_record~");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordPunctureLevel", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("PunctureLevels")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_puncture_levels_anesthesia_records_anesth~");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordStimulatedNerve", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithMany("StimulatedNerves")
                        .HasForeignKey("AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_anesthesia_record_stimulated_nerves_anesthesia_records_anes~");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.ClinicalEvent", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany("ClinicalEvents")
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_clinical_events__monitoring_records_monitoring_record_id");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.CustomField", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", null)
                        .WithMany("CustomFields")
                        .HasForeignKey("vital_sign_record_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_custom_fields__vital_sign_records_vital_sign_record_id");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.FluidBalance", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany("FluidBalances")
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fluid_balances__monitoring_records_monitoring_record_id");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", "AnesthesiaRecord")
                        .WithOne("MonitoringRecord")
                        .HasForeignKey("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "AnesthesiaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_monitoring_records_anesthesia_records_anesthesia_record_id");

                    b.Navigation("AnesthesiaRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PatientPosition", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany("Positions")
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_patient_position_monitoring_records_monitoring_record_id");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "FirstAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("first_anesthesiologist_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_pre_anesthesia_records__users_first_anesthesiologist_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "SecondAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("second_anesthesiologist_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_pre_anesthesia_records__users_second_anesthesiologist_id");

                    b.Navigation("FirstAnesthesiologist");

                    b.Navigation("SecondAnesthesiologist");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", "MonitoringRecord")
                        .WithMany("VitalSigns")
                        .HasForeignKey("MonitoringRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_vital_sign_records_monitoring_records_monitoring_record_id");

                    b.Navigation("MonitoringRecord");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", b =>
                {
                    b.Navigation("AirwayDevices");

                    b.Navigation("Antibiotics");

                    b.Navigation("MonitoringRecord");

                    b.Navigation("OxygenSupplementationTypes");

                    b.Navigation("PunctureLevels");

                    b.Navigation("StimulatedNerves");

                    b.Navigation("Surgeries");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecordAntibiotic", b =>
                {
                    b.Navigation("Boosters");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.MonitoringRecord", b =>
                {
                    b.Navigation("AdministeredAgents");

                    b.Navigation("ClinicalEvents");

                    b.Navigation("FluidBalances");

                    b.Navigation("Positions");

                    b.Navigation("VitalSigns");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.Procedure", b =>
                {
                    b.Navigation("AnesthesiaRecords");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.VitalSignRecord", b =>
                {
                    b.Navigation("CustomFields");
                });
#pragma warning restore 612, 618
        }
    }
}
