// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UFF.FichaAnestesica.Infra.Context;

#nullable disable

namespace UFF.FichaAnestesica.Infra.Migrations
{
    [DbContext(typeof(SigaDbCtx))]
    partial class SigaDbCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("siga_db")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("activity_score");

                    b.Property<string>("AirwayDeviceNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("airway_device_number");

                    b.Property<int?>("AirwayDeviceType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_device_type");

                    b.Property<int?>("AirwayType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_type");

                    b.Property<TimeOnly>("AnesthesiaEndTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_end_time");

                    b.Property<bool>("AnesthesiaEquipmentChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthesia_equipment_checked");

                    b.Property<TimeOnly>("AnesthesiaStartTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_start_time");

                    b.Property<bool>("AnestheticConsentSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthetic_consent_signed");

                    b.Property<int>("AsaClassification")
                        .HasColumnType("integer")
                        .HasColumnName("asa_classification");

                    b.Property<string>("Assistant")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("assistant");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<bool>("Bronchofibroscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("bronchofibroscopy");

                    b.Property<int>("CirculationScore")
                        .HasColumnType("integer")
                        .HasColumnName("circulation_score");

                    b.Property<int>("ClinicalDischargeCondition")
                        .HasColumnType("integer")
                        .HasColumnName("clinical_discharge_condition");

                    b.Property<bool>("Co2AbsorberCircuit")
                        .HasColumnType("boolean")
                        .HasColumnName("co2_absorber_circuit");

                    b.Property<int>("ConsciousnessScore")
                        .HasColumnType("integer")
                        .HasColumnName("consciousness_score");

                    b.Property<int?>("ControlledVentilationMode")
                        .HasColumnType("integer")
                        .HasColumnName("controlled_ventilation_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("Destination")
                        .HasColumnType("integer")
                        .HasColumnName("destination");

                    b.Property<bool>("DifficultVenousPuncture")
                        .HasColumnType("boolean")
                        .HasColumnName("difficult_venous_puncture");

                    b.Property<string>("ExternalPatientId")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("patient_id");

                    b.Property<int?>("FirstAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("first_anesthesiologist_id");

                    b.Property<bool>("GeneralAnesthesia")
                        .HasColumnType("boolean")
                        .HasColumnName("general_anesthesia");

                    b.Property<bool>("HasPain")
                        .HasColumnType("boolean")
                        .HasColumnName("has_pain");

                    b.Property<int?>("IntubationDifficulty")
                        .HasColumnType("integer")
                        .HasColumnName("intubation_difficulty");

                    b.Property<bool>("Laryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("laryngoscopy");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<bool>("NasalTube")
                        .HasColumnType("boolean")
                        .HasColumnName("nasal_tube");

                    b.Property<bool>("OralTube")
                        .HasColumnType("boolean")
                        .HasColumnName("oral_tube");

                    b.Property<string>("OtherAirwayTechnique")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_technique");

                    b.Property<string>("OtherAirwayTypeDescription")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_type_description");

                    b.Property<int>("OxygenSaturation")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation");

                    b.Property<int>("OxygenSaturationScore")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation_score");

                    b.Property<bool>("OxygenSupplementation")
                        .HasColumnType("boolean")
                        .HasColumnName("oxygen_supplementation");

                    b.Property<bool>("PatientIdentifiedBeforeInduction")
                        .HasColumnType("boolean")
                        .HasColumnName("patient_identified_before_induction");

                    b.Property<bool>("PlexusBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("plexus_block_performed");

                    b.Property<string>("PostOperativeDiagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_operative_diagnosis");

                    b.Property<bool>("PreAnestheticMedication")
                        .HasColumnType("boolean")
                        .HasColumnName("pre_anesthetic_medication");

                    b.Property<string>("PreOperativeDiagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pre_operative_diagnosis");

                    b.Property<bool>("ProphylacticAntibioticUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("prophylactic_antibiotic_used");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("RespirationMode")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_mode");

                    b.Property<int>("RespirationScore")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_score");

                    b.Property<int>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<bool>("RetrogradeTechnique")
                        .HasColumnType("boolean")
                        .HasColumnName("retrograde_technique");

                    b.Property<TimeOnly>("RoomEntryTime")
                        .HasColumnType("time")
                        .HasColumnName("room_entry_time");

                    b.Property<string>("SafetyObservations")
                        .HasColumnType("text")
                        .HasColumnName("safety_observations");

                    b.Property<int?>("SecondAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("second_anesthesiologist_id");

                    b.Property<bool>("SedationPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("sedation_performed");

                    b.Property<bool>("SpinalBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("spinal_block_performed");

                    b.Property<string>("Surgeon")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("surgeon");

                    b.Property<TimeOnly>("SurgeryEndTime")
                        .HasColumnType("time")
                        .HasColumnName("surgery_end_time");

                    b.Property<string>("SurgeryPerformed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surgery_performed");

                    b.Property<int>("SurgicalPosition")
                        .HasColumnType("integer")
                        .HasColumnName("surgical_position");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<int>("TotalAldreteKroulikScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_aldrete_kroulik_score");

                    b.Property<bool>("Tracheostomy")
                        .HasColumnType("boolean")
                        .HasColumnName("tracheostomy");

                    b.Property<bool>("UsesCushions")
                        .HasColumnType("boolean")
                        .HasColumnName("uses_cushions");

                    b.Property<string>("VenousAccessLocation")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("venous_access_location");

                    b.Property<int>("VenousAccessType")
                        .HasColumnType("integer")
                        .HasColumnName("venous_access_type");

                    b.Property<bool>("VideoLaryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("video_laryngoscopy");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("FirstAnesthesiologistId");

                    b.HasIndex("SecondAnesthesiologistId");

                    b.ToTable("anesthesia_records", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("activity_score");

                    b.Property<string>("AirwayDeviceNumber")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("airway_device_number");

                    b.Property<int?>("AirwayDeviceType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_device_type");

                    b.Property<int?>("AirwayType")
                        .HasColumnType("integer")
                        .HasColumnName("airway_type");

                    b.Property<TimeOnly>("AnesthesiaEndTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_end_time");

                    b.Property<bool>("AnesthesiaEquipmentChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthesia_equipment_checked");

                    b.Property<TimeOnly>("AnesthesiaStartTime")
                        .HasColumnType("time")
                        .HasColumnName("anesthesia_start_time");

                    b.Property<bool>("AnestheticConsentSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("anesthetic_consent_signed");

                    b.Property<int>("AsaClassification")
                        .HasColumnType("integer")
                        .HasColumnName("asa_classification");

                    b.Property<string>("Assistant")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("assistant");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<bool>("Bronchofibroscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("bronchofibroscopy");

                    b.Property<int>("CirculationScore")
                        .HasColumnType("integer")
                        .HasColumnName("circulation_score");

                    b.Property<int>("ClinicalDischargeCondition")
                        .HasColumnType("integer")
                        .HasColumnName("clinical_discharge_condition");

                    b.Property<bool>("Co2AbsorberCircuit")
                        .HasColumnType("boolean")
                        .HasColumnName("co2_absorber_circuit");

                    b.Property<int>("ConsciousnessScore")
                        .HasColumnType("integer")
                        .HasColumnName("consciousness_score");

                    b.Property<int?>("ControlledVentilationMode")
                        .HasColumnType("integer")
                        .HasColumnName("controlled_ventilation_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("Destination")
                        .HasColumnType("integer")
                        .HasColumnName("destination");

                    b.Property<bool>("DifficultVenousPuncture")
                        .HasColumnType("boolean")
                        .HasColumnName("difficult_venous_puncture");

                    b.Property<int>("FirstAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("first_anesthesiologist_id");

                    b.Property<bool>("GeneralAnesthesia")
                        .HasColumnType("boolean")
                        .HasColumnName("general_anesthesia");

                    b.Property<bool>("HasPain")
                        .HasColumnType("boolean")
                        .HasColumnName("has_pain");

                    b.Property<int?>("IntubationDifficulty")
                        .HasColumnType("integer")
                        .HasColumnName("intubation_difficulty");

                    b.Property<bool>("Laryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("laryngoscopy");

                    b.Property<DateTime?>("LastLoginAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<bool>("NasalTube")
                        .HasColumnType("boolean")
                        .HasColumnName("nasal_tube");

                    b.Property<bool>("OralTube")
                        .HasColumnType("boolean")
                        .HasColumnName("oral_tube");

                    b.Property<string>("OtherAirwayTechnique")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_technique");

                    b.Property<string>("OtherAirwayTypeDescription")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("other_airway_type_description");

                    b.Property<int>("OxygenSaturation")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation");

                    b.Property<int>("OxygenSaturationScore")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation_score");

                    b.Property<bool>("OxygenSupplementation")
                        .HasColumnType("boolean")
                        .HasColumnName("oxygen_supplementation");

                    b.Property<bool>("PatientIdentifiedBeforeInduction")
                        .HasColumnType("boolean")
                        .HasColumnName("patient_identified_before_induction");

                    b.Property<bool>("PlexusBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("plexus_block_performed");

                    b.Property<string>("PostOperativeDiagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_operative_diagnosis");

                    b.Property<bool>("PreAnestheticMedication")
                        .HasColumnType("boolean")
                        .HasColumnName("pre_anesthetic_medication");

                    b.Property<string>("PreOperativeDiagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pre_operative_diagnosis");

                    b.Property<bool>("ProphylacticAntibioticUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("prophylactic_antibiotic_used");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("RespirationMode")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_mode");

                    b.Property<int>("RespirationScore")
                        .HasColumnType("integer")
                        .HasColumnName("respiration_score");

                    b.Property<int>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<bool>("RetrogradeTechnique")
                        .HasColumnType("boolean")
                        .HasColumnName("retrograde_technique");

                    b.Property<TimeOnly>("RoomEntryTime")
                        .HasColumnType("time")
                        .HasColumnName("room_entry_time");

                    b.Property<string>("SafetyObservations")
                        .HasColumnType("text")
                        .HasColumnName("safety_observations");

                    b.Property<int>("SecondAnesthesiologistId")
                        .HasColumnType("integer")
                        .HasColumnName("second_anesthesiologist_id");

                    b.Property<bool>("SedationPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("sedation_performed");

                    b.Property<bool>("SpinalBlockPerformed")
                        .HasColumnType("boolean")
                        .HasColumnName("spinal_block_performed");

                    b.Property<string>("Surgeon")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("surgeon");

                    b.Property<TimeOnly>("SurgeryEndTime")
                        .HasColumnType("time")
                        .HasColumnName("surgery_end_time");

                    b.Property<string>("SurgeryPerformed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surgery_performed");

                    b.Property<int>("SurgicalPosition")
                        .HasColumnType("integer")
                        .HasColumnName("surgical_position");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<int>("TotalAldreteKroulikScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_aldrete_kroulik_score");

                    b.Property<bool>("Tracheostomy")
                        .HasColumnType("boolean")
                        .HasColumnName("tracheostomy");

                    b.Property<bool>("UsesCushions")
                        .HasColumnType("boolean")
                        .HasColumnName("uses_cushions");

                    b.Property<string>("VenousAccessLocation")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("venous_access_location");

                    b.Property<int>("VenousAccessType")
                        .HasColumnType("integer")
                        .HasColumnName("venous_access_type");

                    b.Property<bool>("VideoLaryngoscopy")
                        .HasColumnType("boolean")
                        .HasColumnName("video_laryngoscopy");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.Property<int>("first_anesthesiologist_id")
                        .HasColumnType("integer");

                    b.Property<int>("second_anesthesiologist_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("first_anesthesiologist_id");

                    b.HasIndex("second_anesthesiologist_id");

                    b.ToTable("pre_anesthesia_records", "siga_db", t =>
                        {
                            t.Property("first_anesthesiologist_id")
                                .HasColumnName("first_anesthesiologist_id1");

                            t.Property("second_anesthesiologist_id")
                                .HasColumnName("second_anesthesiologist_id1");
                        });
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanLogIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_login");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("LastLoginAt")
                        .IsRequired()
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_sync_at");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_update");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("registration");

                    b.Property<string>("Sector")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sector");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CanLogIn");

                    b.HasIndex("Email");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("users", "siga_db");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.AnesthesiaRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "FirstAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("FirstAnesthesiologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_record__users_first_anesthesiologist_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "SecondAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("SecondAnesthesiologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_anesthesia_record__users_second_anesthesiologist_id");

                    b.Navigation("FirstAnesthesiologist");

                    b.Navigation("SecondAnesthesiologist");
                });

            modelBuilder.Entity("UFF.FichaAnestesica.Domain.Entities.PreAnesthesiaRecord", b =>
                {
                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "FirstAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("first_anesthesiologist_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_pre_anesthesia_record__users_first_anesthesiologist_id");

                    b.HasOne("UFF.FichaAnestesica.Domain.Entities.User", "SecondAnesthesiologist")
                        .WithMany()
                        .HasForeignKey("second_anesthesiologist_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_pre_anesthesia_record__users_second_anesthesiologist_id");

                    b.Navigation("FirstAnesthesiologist");

                    b.Navigation("SecondAnesthesiologist");
                });
#pragma warning restore 612, 618
        }
    }
}
