<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Commands\AnesthesiaRecord\AnesthesiaRecordCommand.cs~RF46a311a.TMP" />
    <None Remove="Commands\AnesthesiaRecord\MonitoringRecordCommand.cs~RF10973372.TMP" />
    <None Remove="Dto\MonitoringRecordDto.cs~RF109620d9.TMP" />
    <None Remove="Dto\PatientDto.cs~RF6a792ed.TMP" />
    <None Remove="Dto\UserDto.cs~RF74b85f0.TMP" />
    <None Remove="Entities\AdministeredAgent.cs~RF20a31a.TMP" />
    <None Remove="Entities\AnesthesiaRecord.cs~RF4a0de5a.TMP" />
    <None Remove="Entities\AnesthesiaRecord.cs~RFc19c74.TMP" />
    <None Remove="Entities\FluidBalance.cs~RF290373.TMP" />
    <None Remove="Entities\FluidBalance.cs~RF2a29f2.TMP" />
    <None Remove="Entities\FluidBalance.cs~RF511718.TMP" />
    <None Remove="Entities\FluidBalance.cs~RF549726.TMP" />
    <None Remove="Entities\jvjfzato.mov~" />
    <None Remove="Entities\l0iyuavp.pq5~" />
    <None Remove="Entities\MonitoringRecord.cs~RF10946241.TMP" />
    <None Remove="Entities\Patient.cs~RF2dc167d.TMP" />
    <None Remove="Entities\User.cs~RF4027d567.TMP" />
    <None Remove="Entities\User.cs~RF402958ea.TMP" />
    <None Remove="Entities\User.cs~RF4062cc21.TMP" />
    <None Remove="Entities\User.cs~RF7ddc786.TMP" />
    <None Remove="Entities\User.cs~RF7e6f467.TMP" />
    <None Remove="Entities\User.cs~RF8205b0b.TMP" />
    <None Remove="Enums\ClinicalDischargeCondition.cs~RFd4d9ed.TMP" />
    <None Remove="Repositories\IAnesthesiaRecordRepository.cs~RF4815b56.TMP" />
    <None Remove="Repositories\IAnesthesiaRecordRepository.cs~RFe51439.TMP" />
    <None Remove="Repositories\IUserRepository.cs~RF4dacd3.TMP" />
    <None Remove="Repositories\IUserRepository.cs~RF7c5d333.TMP" />
    <None Remove="Repositories\ReadOnly\IHospitalApiRepository.cs~RF93d82fb.TMP" />
    <None Remove="Response\PatientLocationResponse.cs~RFcabe48.TMP" />
    <None Remove="Response\PatientSurgeryResponse.cs~RF6a9299b.TMP" />
    <None Remove="Response\UnitResponse.cs~RFcc8992.TMP" />
    <None Remove="Services\IAnesthesiaRecordService.cs~RF46f688d.TMP" />
    <None Remove="Services\IPdfService.cs~RFb5f9839.TMP" />
    <None Remove="Services\IProfessionalsService.cs~RF92fa647.TMP" />
    <None Remove="Services\ISurgeryService.cs~RF225a8f3.TMP" />
    <None Remove="Services\ISurgeryService.cs~RFdc1d0f.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.25" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>

</Project>
